#!/usr/bin/env bash
# Generate IreeRuntimePin.cmake -- URL + SHA-256 per variant/platform.
#
# This replaces the consumer's stub seam native/cmake/IreeRuntimePin.cmake.
# Recording the hash means FetchContent re-verifies the tarball on every build,
# which is the supply-chain review gate.
set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
. "$HERE/lib/naming.sh"
. "$HERE/lib/variants.sh"

REPO="${1:?usage: gen-pin.sh <owner/repo> <tag> <version> <assets-dir> <outfile>}"
TAG="${2:?tag required}"
VERSION="${3:?version required}"
ASSETS="${4:?assets dir required}"
OUTFILE="${5:?outfile required}"

PLATFORMS="linux-x86_64"

{
  echo "# Generated by iree-runtime-dist gen-pin.sh -- do not edit."
  echo "# Release: $TAG"
  echo "#"
  echo "# Paste into a consuming project and FetchContent the pinned tarball;"
  echo "# the recorded SHA-256 is re-verified on every build."
  echo ""
  for variant in $(known_variants); do
    for platform in $PLATFORMS; do
      tb="$(tarball_name "$VERSION" "$variant" "$platform")"
      shafile="$ASSETS/$(sha_name "$VERSION" "$variant" "$platform")"
      if [ ! -f "$shafile" ]; then
        echo "error: missing sha file $shafile" >&2
        exit 1
      fi
      sha="$(cut -d' ' -f1 < "$shafile")"
      echo "set(IREE_RUNTIME_URL_${variant}_${platform}"
      echo "    \"https://github.com/${REPO}/releases/download/${TAG}/${tb}\")"
      echo "set(IREE_RUNTIME_SHA256_${variant}_${platform}"
      echo "    \"${sha}\")"
      echo ""
    done
  done
} > "$OUTFILE"

echo "==> generated $OUTFILE"
