#!/usr/bin/env bash
# Generate IreeRuntimePin.cmake -- URL + SHA-256 per variant/platform.
#
# This replaces the consumer's stub seam native/cmake/IreeRuntimePin.cmake.
# Recording the hash means FetchContent re-verifies the tarball on every build,
# which is the supply-chain review gate.
set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
. "$HERE/lib/naming.sh"
. "$HERE/lib/variants.sh"

REPO="${1:?usage: gen-pin.sh <owner/repo> <tag> <version> <assets-dir> <outfile>}"
TAG="${2:?tag required}"
VERSION="${3:?version required}"
ASSETS="${4:?assets dir required}"
OUTFILE="${5:?outfile required}"

# PLATFORMS comes from scripts/lib/naming.sh (single source of truth --
# see Finding 6/the design's §4 single-source-of-truth discipline).

{
  echo "# Generated by iree-runtime-dist gen-pin.sh -- do not edit."
  echo "# Release: $TAG"
  echo "#"
  echo "# Select a variant with the helper below; FetchContent only the pair it"
  echo "# returns, so unused variants download nothing:"
  echo "#   iree_runtime_dist_url(\"\${IREE_RUNTIME_VARIANT}\" \"\${platform}\" url sha)"
  echo ""
  for variant in $(known_variants); do
    for platform in $PLATFORMS; do
      tb="$(tarball_name "$VERSION" "$variant" "$platform")"
      shafile="$ASSETS/$(sha_name "$VERSION" "$variant" "$platform")"
      [ -f "$shafile" ] || { echo "error: missing sha file $shafile" >&2; exit 1; }
      sha="$(cut -d' ' -f1 < "$shafile")"
      echo "set(IREE_RUNTIME_DIST_${variant}_${platform}_URL"
      echo "    \"https://github.com/${REPO}/releases/download/${TAG}/${tb}\")"
      echo "set(IREE_RUNTIME_DIST_${variant}_${platform}_SHA256 \"${sha}\")"
      echo ""
    done
  done
  cat <<'EOF'
# Fixed selector -- the consumer calls this, never string-builds a variable name.
function(iree_runtime_dist_url variant platform out_url out_sha)
  set(_k "${variant}_${platform}")
  if(NOT DEFINED IREE_RUNTIME_DIST_${_k}_URL)
    message(FATAL_ERROR
      "iree-runtime-dist: no artifact for variant='${variant}' platform='${platform}'")
  endif()
  set(${out_url} "${IREE_RUNTIME_DIST_${_k}_URL}" PARENT_SCOPE)
  set(${out_sha} "${IREE_RUNTIME_DIST_${_k}_SHA256}" PARENT_SCOPE)
endfunction()
EOF
} > "$OUTFILE"

echo "==> generated $OUTFILE"
