#!/usr/bin/env bash
# Generate IreeRuntimePin.cmake -- URL + SHA-256 per variant/platform.
#
# This replaces the consumer's stub seam native/cmake/IreeRuntimePin.cmake.
# Recording the hash means FetchContent re-verifies the tarball on every build,
# which is the supply-chain review gate.
#
# The rows come from the assets on disk, not from declared variant/platform
# lists: every *.sha256 in <assets-dir> is parsed with naming.sh's parse_asset
# (the inverse of asset_stem) and gets a pin entry. A zero-row scan (broken
# download) or a malformed sha fails loudly below, so the pin can never
# reference an asset that was never built, nor omit one that was.
set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
. "$HERE/lib/naming.sh"

REPO="${1:?usage: gen-pin.sh <owner/repo> <tag> <version> <assets-dir> <outfile>}"
TAG="${2:?tag required}"
VERSION="${3:?version required}"
ASSETS="${4:?assets dir required}"
OUTFILE="${5:?outfile required}"

# Collect rows first so a broken download aborts before a short pin is written.
# parse_asset's exit 2 (bad name) surfaces as read hitting EOF; the `|| exit 1`
# propagates it out of the subshell, failing the assignment under set -e.
rows="$(
  for shafile in "$ASSETS"/*.sha256; do
    [ -e "$shafile" ] || continue
    b="$(basename "$shafile")"
    read -r v variant platform < <(parse_asset "$b") || exit 1
    [ "$v" = "$VERSION" ] \
      || { echo "gen-pin: '$b' carries version $v, expected $VERSION" >&2; exit 1; }
    sha_hex="$(cut -d' ' -f1 "$shafile")"
    case "$sha_hex" in
      ""|*[!0-9a-f]*) echo "gen-pin: '$b' has a malformed sha256 ('$sha_hex')" >&2; exit 1 ;;
    esac
    [ "${#sha_hex}" -eq 64 ] \
      || { echo "gen-pin: '$b' sha256 is not 64 hex chars ('$sha_hex')" >&2; exit 1; }
    printf '%s\t%s\t%s\n' "$variant" "$platform" "$sha_hex"
  done
)"
[ -n "$rows" ] \
  || { echo "gen-pin: no *.sha256 assets in '$ASSETS' -- nothing to pin" >&2; exit 1; }

{
  echo "# Generated by iree-runtime-dist gen-pin.sh -- do not edit."
  echo "# Release: $TAG"
  echo "#"
  echo "# Select a variant with the helper below; FetchContent only the pair it"
  echo "# returns, so unused variants download nothing:"
  echo "#   iree_runtime_dist_url(\"\${IREE_RUNTIME_VARIANT}\" \"\${platform}\" url sha)"
  echo ""
  # Sorted platform-major for deterministic output (same sort as
  # executorch-runtime-dist's discover-pin-rows.sh).
  while IFS=$'\t' read -r variant platform sha; do
    tb="$(tarball_name "$VERSION" "$variant" "$platform")"
    echo "set(IREE_RUNTIME_DIST_${variant}_${platform}_URL"
    echo "    \"https://github.com/${REPO}/releases/download/${TAG}/${tb}\")"
    echo "set(IREE_RUNTIME_DIST_${variant}_${platform}_SHA256 \"${sha}\")"
    echo ""
  done < <(printf '%s\n' "$rows" | sort -t"$(printf '\t')" -k2,2 -k1,1)
  cat <<'EOF'
# Fixed selector -- the consumer calls this, never string-builds a variable name.
function(iree_runtime_dist_url variant platform out_url out_sha)
  set(_k "${variant}_${platform}")
  if(NOT DEFINED IREE_RUNTIME_DIST_${_k}_URL)
    message(FATAL_ERROR
      "iree-runtime-dist: no artifact for variant='${variant}' platform='${platform}'")
  endif()
  set(${out_url} "${IREE_RUNTIME_DIST_${_k}_URL}" PARENT_SCOPE)
  set(${out_sha} "${IREE_RUNTIME_DIST_${_k}_SHA256}" PARENT_SCOPE)
endfunction()
EOF
} > "$OUTFILE"

echo "==> generated $OUTFILE"
